### ISSUE TITLE
Properties added through data are assigned to this and this.$

### ISSUE THREAD

**Issue by MikaAK** [davej/angular-classy#39]
Recently I noticed that data that has been assigned via the `data: {}` property will not only get put on `this.$` but also on `this`.
Assigning properties via  `this.$.myProp = { a: 1, b: 2}` only inserts them on scope and doesn't put them onto the `this` object of the controller.

**Comment by davej** [comment]
This is now fixed in master.

Example Usage:

```
angular.module('app').classy.options.controller = {
    bindData: {
        addToClass: false
    }
}
```
