### ISSUE TITLE
Can I have the sourcemap?

### ISSUE THREAD

**Issue by edwardbrosens** [davej/angular-classy#45]

**Comment by davej** [comment]
Sourcemap for what?

**Comment by edwardbrosens** [comment]
I would like to use the minified version,  but I would also like to debug
the source.

Regards,
Edward Brosens
 Op 23 apr. 2015 16:44 schreef "Dave Jeffery" <notifications@github.com>:

**Comment by davej** [comment]
Ah ok, I'll add a map for the minified version in the next release.

**Comment by edwardbrosens** [comment]
Thanks.  :')
