### ISSUE TITLE
Disable the scope inclusion of all methods.

### ISSUE THREAD

**Issue by fabulouslord** [davej/angular-classy#46]
Is this possible? I would like to prefix with _ the methods utilized by other public methods but don't expose this public ones as they get put directly into the scope, which is widely recognized as a bad practice. 

E.g. 

    init : function(){
        this.$scope.qt = {
            user: user,
            getToken: this.getToken
        };
    },
    methods : {
	    getToken : function(){
		    // A method I don't want to put directly on the scope
	    }
    }

So instead of calling it like

    <button ng-click="getToken()"></button>
    
    
I can call it like 

    <button ng-click="qt.getToken()"></button>

but currently the method would be still be put into the scope directly and I could call it either way, which I do not want to.

I hope I make sense, and look forward to a reply.

**Comment by davej** [comment]
I'm sorry I don't really understand your question. Methods prefixed with `_` currently won't be put in the scope.

If you're worried about `$scope` pollution then you should look into the 'contoller as' syntax, it is compatible with Classy and will give you what _I think_ you're looking for.

**Comment by fabulouslord** [comment]
What I mean is that I don't want non "_" prefixed methods to be put into the scope as well, as they pollute the scope and I would like to put them into an object and expose the object instead, while still being able to utilize the underscore to denote private methods and non "_" prefixed methods to denote public methods. What is it that "controller as" syntax? , couldn't find any reference.

Cheers.

**Comment by davej** [comment]
You can do this globally with:
```javascript
myApp.classy.options.controller = {
  addToScope: false
};
```

or on a per-controller basis
```javascript
myApp.classy.controller({
  name: 'TodoCtrl',
  inject: ['$scope', 'filterFilter'],
  __options: {
      addToScope: false
  }
  // ...
});
```

More info on controller-as here: http://toddmotto.com/digging-into-angulars-controller-as-syntax/
Also check out the FAQs here: http://davej.github.io/angular-classy/

**Comment by davej** [comment]
By the way if you only want to apply this behaviour to methods (and not the `data` object) then you could do this:

```javascript
myApp.classy.options.controller = {
  bindMethods: {
    addToScope: false
  }
};
```

Does that answer all your questions?

**Comment by fabulouslord** [comment]
Yes it does Dave! Thanks for the quick feedback!
