### ISSUE TITLE
angular ui router: state resolve not working with angular classy

### ISSUE THREAD

**Issue by janbee** [davej/angular-classy#51]
Hi, Im using 1.2.4 classy, I have an issue using ui router resolve

      `$stateProvider.state({
            name: 'public',
            url: '',
            views:{
                'main' : {template: '<public data="$resolve.$test""/>'}
            },
            resolve: {
                $test: function($stateParams, $http) {
                    return $http.post('/me',{});
                }
            }
        })`

using the normal this is working with $onInit

    `app.component('public', {
        template: require('./public.html'),
        bindings: {data: '='},
        controller:  function(){
            var self = this;
            this.$onInit = function(){
                console.log("-------------------------",self.data);
            }
        }
    })`

in angular classy init:function its not

any advice?

**Comment by davej** [comment]
I haven't tested with ui-router resolvers but I can do a bit of debugging if you're able to provide a [plunkr](https://plnkr.co/) of what you're trying to do.

**Comment by janbee** [comment]
I made it work, seems like its working like this

publicMod.component('public', {
     template: require('./public.html'), bindings: {
         $me:'<' }, controller:  publicMod.classy.controller({
         name :'PublicCtrl', inject:['$scope','$state','$element'], methods: {
             $onInit:function(){
                 let self =this; console.log("2cheasdasdadasck data",self.$me); }
         }

     })
});

the "self.$me" var is the promise from ui router resolve. But is it safe 
to use the $onInit?, just like using it on the old component way like below

|.component('myPane',{controller:function(){this.$onInit 
=function(){console.log(this);};},templateUrl:'my-pane.html'});|

Cheers, Janbee

**Comment by davej** [comment]
It's difficult for me to debug because I'm not familiar with ui-router. If you put it in a plunkr then I should be able to answer you better.
