### ISSUE TITLE
classy 1.2.4 - inject objecy

### ISSUE THREAD

**Issue by janbee** [davej/angular-classy#52]
Hi Dave, 

http://davej.github.io/angular-classy/0.4.html

state that you can specify injectables like

inject: {
    $scope: '$',
    filterFilter: 'filter',
    $location: '.'
  },

Im using 1.2.4 and i cant make this work.

**Comment by davej** [comment]
I had to check through the code and [plugins](https://libraries.io/search?keywords=classy-plugin&platforms=Bower&q=&sort=) to be sure but it was removed from 1.0. Sorry about that.
